### ISSUE TITLE
Error level and extra on messages with new Capture API.

### ISSUE THREAD

**Issue by jmalczak** [getsentry/raven-csharp#109] opened 2016-03-13 07:01 UTC
Hi, is there any way to set level to Info and to add extra objects to messages when you use new Capture API (CaptureMessage is marked as obsolete)? I have tried: 

Capture(new SentryEvent(new SentryMessage(message)) { Extra = myObj });

but it didn't work for me. Setting level this way didn't work either. I have always log level Error.

Thanks

**Comment by asbjornu** [comment] 2016-03-17 20:59
@jmalczak The new `SentryEvent` code path was not water tight, to say the least. I think I've plugged the holes and covered them with a lot of more tests now, so please have a go at [2.1 prerelease on NuGet](https://www.nuget.org/packages/SharpRaven/2.1.0-unstable0020) and report back whether fixes the problem or not.

**Comment by asbjornu** [comment] 2016-03-30 13:45
@jmalczak You were correct, `LogLevel` was indeed missing. @xpicio was kind and fixed that in #117, which is merged and included in the [latest prerelease on NuGet](https://www.nuget.org/packages/SharpRaven/2.1.0-unstable0025). Please test it and report back whether it fixes the problem or not.

**Comment by mogikanin** [comment] 2016-03-31 03:28
Also tags are missed. Here the sample with old approach which works fine, and similar code for Capture method which doesn't work (tried only 2.0 release)

```
 private string CaptureMessage(SentryMessage log)
        {
            var sentryLevel = FromLogLevel(log.Level);

            // Old approach
            var tags = CommonTags;
            var sentryId = log.Exception == null
               ? _ravenClient.CaptureMessage(log.Message, sentryLevel, tags, extra: log.Extra)
               : _ravenClient.CaptureException(log.Exception, log.Message, sentryLevel, tags, extra: log.Extra);

            // New API
            var @event = new SentryEvent(log.Exception)
            {
                Message = log.Message,
                Level = sentryLevel,
                Extra = log.Extra,
            };
            foreach (var commonTag in CommonTags)
            {
                @event.Tags.Add(commonTag.Key, commonTag.Value);
            }
            sentryId = _ravenClient.Capture(@event);       
            return sentryId;
        }
```

**Comment by asbjornu** [comment] 2016-04-01 12:03
@mogikanin The [`MergeTags()`](https://github.com/getsentry/raven-csharp/blob/develop/src/app/SharpRaven/RavenClient.cs#L413) method should assure that tags are properly merged and as you can see [here](https://github.com/getsentry/raven-csharp/blob/develop/src/app/SharpRaven/RavenClient.cs#L183), the tags are set. The [`TagHandling`](https://github.com/getsentry/raven-csharp/blob/develop/src/tests/SharpRaven.UnitTests/RavenClientTests/CaptureTests.cs#L131) test should also verify that this is working.

Can you please test with the latest pre-release and if it doesn't work, either point out why it isn't working or submit a pull request with a failing test?

**Comment by mogikanin** [comment] 2016-04-02 04:00
@asbjornu Latest pre-release works fine.

**Comment by asbjornu** [comment] 2016-04-02 09:14
@mogikanin Excellent! How does it work for you, @jmalczak?

**Comment by jmalczak** [comment] 2016-04-02 10:16
Sorry guys. I have decided to use obsolete api for now, so I couldn't check if issue have been fixed. Since @mogikanin confirms it works fine. Feel free to close issue. Thanks!

**Comment by asbjornu** [comment] 2016-04-02 19:32
@jmalczak Ok, I hope the problem is fixed even though you haven't had the opportunity to test it yet. Please report back when you do if something's odd. Thanks! :smiley:

**Closed by asbjornu** 2016-04-02 19:32 UTC
