### ISSUE TITLE
Exceptions not being posted from within Unity (4.5.5f1)

### ISSUE THREAD

**Issue by PsychoTea** [getsentry/raven-csharp#196] opened 2017-11-19 22:39 UTC
I'm using the following code, and attempting to post exceptions with it from within a Unity game:

```c#
using System;
using SharpRaven;
using SharpRaven.Data;

namespace PsychoMod.Logging
{
    public static class Sentry
    {
        private static RavenClient ravenClient;

        public static void Initialize()
        {
            if (ravenClient != null) return;

            ravenClient = new RavenClient("<url here>");
        }

        public static void LogException(Exception ex) => ravenClient.Capture(new SentryEvent(ex));
    }
}
```

However, any exceptions passed to `Sentry.LogException` are never logged to the dashboard. The same code works fine from a separate program (also using .NET 3.5), however not from within the game. No errors occur and everything _appears_ to be fine.

All dependencies (Newtonsoft.JSON v6.0.0.0, System.Data 2.0.0.0, and System.Web 2.0.0.0) are loaded, however it still fails to work.

It's worth noting Unity 4.5 uses .NET 3.5, however even when targeting .NET 3.5 in an external program, the library continues to function correctly. It's only when placed into the game engine that it stops functioning.

**Comment by asbjornu** [comment] 2017-11-21 14:47
Isn't this a duplicate of #193, #145, #126, #70 and #60?

**Comment by asbjornu** [comment] 2018-03-05 20:48
[SharpRaven version `2.2.1-unstable0059`](https://www.nuget.org/packages/SharpRaven/2.2.1-unstable0059) was just published to NuGet.org that might help with this. Please test it and report back your status. Thanks!

**Comment by bruno-garcia** [comment] 2018-10-11 12:25
@PsychoTea Sorry for getting to this thread so late.
Do you still use Unity 4.5.5?
Sentry is aiming Unity support now and [I'm curious to know which versions are being used](https://twitter.com/brungarc/status/1049630060460867584) out there.

**Comment by PsychoTea** [comment] 2018-10-11 15:04
@asbjornu Sorry for my lack of response, I moved away from the project but will hopefully be able to take a look at it again.

@bruno-garcia Yes, but not through choice 😛 I'm working on a modding platform for a custom version of an old game, so I'm probably in the minority in working on such an old version.

**Comment by bruno-garcia** [comment] 2018-10-11 15:36
@PsychoTea good to know.
What we're working on might be possible to make compatible with 4.5 but I'm not sure we'll take the effort right now.

We're aiming 5.6 right now to get a first version out.
In case you'd like to participate, join the repo:

https://github.com/getsentry/sentry-unity

Feel free to open an issue there and link to this for Unity 4.x support.

**Closed** 2018-10-11 15:41 UTC
Labels: bug
